apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: hello-app
 name: hello-app
spec:
 replicas: 2
 selector:
   matchLabels:
     app: hello-app
 template:
   metadata:
     labels:
       app: hello-app
   spec:
     containers:
     - image:  nginx #pavansa/node-hello-world-example:latest
       name: hello-app
       ports:
       - containerPort: 3007
