pipeline:
  identifier: Build_suddapalli_harness_ci_example_1741015842926
  name: Build harness-ci-example
  orgIdentifier: default
  projectIdentifier: VJnewproject
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1741015816810
        repoName: suddapalli/harness-ci-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  name: docker_build
                  identifier: dockerbuild
                  template:
                    templateRef: vjdockertemplate
                    versionLabel: latest
                    templateInputs:
                      type: BuildAndPushDockerRegistry
                      spec:
                        connectorRef: <+input>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          buildIntelligence:
            enabled: true
        type: CI
        description: ""
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Asg
          service:
            serviceRef: vjservice
          environment:
            environmentRef: vjevn
            deployToAll: false
            infrastructureDefinitions:
              - identifier: vjinfra
          execution:
            steps:
              - step:
                  name: Asg Rolling Deploy
                  identifier: AsgRollingDeploy
                  type: AsgRollingDeploy
                  timeout: 10m
                  spec:
                    useAlreadyRunningInstances: false
            rollbackSteps:
              - step:
                  name: Asg Rolling Rollback
                  identifier: AsgRollingRollback
                  type: AsgRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
